type MockProduct = {
  id: number;
  title: string;
  description: string;
  price: number;
  discountPercentage: number;
  rating: number;
  stock: number;
  category: string;
  images: string[];
  thumbnail: string | null;
};

export const mockProducts: MockProduct[] = [
  {
    id: 9001,
    title: "Volt Arc Sneaker Lamp",
    description: "Mood light for sneaker shelves with sharp neon edge and quiet RGB pulse.",
    price: 79,
    discountPercentage: 29,
    rating: 4.7,
    stock: 22,
    category: "home-decoration",
    images: [],
    thumbnail: null,
  },
  {
    id: 9002,
    title: "Orbit Runner X",
    description: "Lightweight daily sneaker with reflective heel hit and cushioned sole.",
    price: 109,
    discountPercentage: 24,
    rating: 4.8,
    stock: 16,
    category: "mens-shoes",
    images: [],
    thumbnail: null,
  },
  {
    id: 9003,
    title: "Neon Dock Fold",
    description: "Travel dock for phone, tablet and earbuds with fold-flat aluminum body.",
    price: 59,
    discountPercentage: 33,
    rating: 4.5,
    stock: 41,
    category: "mobile-accessories",
    images: [],
    thumbnail: null,
  },
  {
    id: 9004,
    title: "Pulse Carry Tote",
    description: "Structured tote with magnetic compartments and waterproof outer shell.",
    price: 92,
    discountPercentage: 19,
    rating: 4.4,
    stock: 35,
    category: "womens-bags",
    images: [],
    thumbnail: null,
  },
  {
    id: 9005,
    title: "FrameForge Mirror Set",
    description: "Two-piece mirror kit with hidden hooks and smoked edge finish.",
    price: 74,
    discountPercentage: 26,
    rating: 4.6,
    stock: 29,
    category: "home-decoration",
    images: [],
    thumbnail: null,
  },
  {
    id: 9006,
    title: "KiloSound Pods Pro",
    description: "Low-latency earbuds tuned for quick workouts and commute focus.",
    price: 129,
    discountPercentage: 31,
    rating: 4.9,
    stock: 18,
    category: "mobile-accessories",
    images: [],
    thumbnail: null,
  },
  {
    id: 9007,
    title: "Atlas Chrono S",
    description: "Slim watch with bright lume markers and brushed metal bezel.",
    price: 149,
    discountPercentage: 18,
    rating: 4.5,
    stock: 12,
    category: "mens-watches",
    images: [],
    thumbnail: null,
  },
  {
    id: 9008,
    title: "Drift Court LX",
    description: "High-top sneaker with retro paneling and plush ankle lock.",
    price: 119,
    discountPercentage: 27,
    rating: 4.6,
    stock: 26,
    category: "womens-shoes",
    images: [],
    thumbnail: null,
  },
  {
    id: 9009,
    title: "RoomHack Grid Shelf",
    description: "Modular metal shelf built for plants, books and small gear displays.",
    price: 135,
    discountPercentage: 22,
    rating: 4.3,
    stock: 31,
    category: "furniture",
    images: [],
    thumbnail: null,
  },
  {
    id: 9010,
    title: "HyperFrame Tablet Stand",
    description: "Adjustable stand with elevated cooling arc and magnetic cable lane.",
    price: 48,
    discountPercentage: 36,
    rating: 4.7,
    stock: 44,
    category: "tablets",
    images: [],
    thumbnail: null,
  },
  {
    id: 9011,
    title: "Skyline Sport Shield",
    description: "Wraparound shades with contrast lens tint and featherweight temples.",
    price: 67,
    discountPercentage: 21,
    rating: 4.4,
    stock: 27,
    category: "sunglasses",
    images: [],
    thumbnail: null,
  },
  {
    id: 9012,
    title: "VoltGrip Controller Case",
    description: "Hardshell carry case with custom foam and quick-access cable pocket.",
    price: 43,
    discountPercentage: 28,
    rating: 4.8,
    stock: 38,
    category: "sports-accessories",
    images: [],
    thumbnail: null,
  },
];
